### ISSUE TITLE
字符串字面量的联合类型，用mockjs占位符@pick(['A','B','C'])，识别不了

### ISSUE THREAD

**Issue by inceptiongt** [thx/rapper#9]
接口配置该字段（三选一）
![image](https://user-images.githubusercontent.com/20478779/92459882-d0c5dc00-f1f9-11ea-983f-3410704aeca5.png)
期望识别成：indexType: 'A' | 'B' | 'C'类型
现在还是识别成 indexType: string

**Comment by mochen666** [comment]
1.2.0-beta.0 已修复这个问题
